# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aariss <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/07 09:13:20 by aariss            #+#    #+#              #
#    Updated: 2018/10/08 09:09:52 by aariss           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CC = gcc
CFLAGS = -Wextra -Werror -Wall  
HEADERS = -I .
LIBFT_SRCS = ft_atoi.c ft_bzero.c ft_free2d.c ft_isalnum.c \
			 ft_isalpha.c ft_isascii.c ft_isblank.c ft_isdigit.c \
			 ft_islower.c ft_isprint.c ft_isspace.c ft_isupper.c \
			 ft_isxdigit.c ft_itoa.c ft_lstadd.c ft_lstdel.c \
			 ft_lstdelone.c ft_lstiter.c ft_lstmap.c ft_lstnew.c \
			 ft_memalloc.c ft_memccpy.c ft_memchr.c ft_memcmp.c \
			 ft_memcpy.c ft_memdel.c ft_memmove.c ft_memset.c \
			 ft_putchar.c ft_putchar_fd.c ft_putendl.c ft_putendl_fd.c \
			 ft_putnbr.c ft_putnbr_fd.c ft_putstr.c ft_putstr_fd.c \
			 ft_strcat.c ft_strchr.c ft_strclr.c ft_strcmp.c \
			 ft_strcpy.c ft_strdel.c ft_strdup.c ft_strequ.c \
			 ft_striter.c ft_striteri.c ft_strjoin.c ft_strlcat.c \
			 ft_strlen.c ft_strmap.c ft_strmapi.c ft_strncat.c \
			 ft_strncmp.c ft_strncpy.c ft_strnequ.c ft_strnew.c \
			 ft_strnstr.c ft_strrchr.c ft_strsplit.c ft_strstr.c \
			 ft_strlchr.c ft_strsub.c ft_strtrim.c ft_tolower.c \
			 ft_toupper.c ft_strndup.c ft_replace_str.c ft_strjoin_f.c

LIBFT_OBJS = $(LIBFT_SRCS:%.c=%.o)

BoldBlue = \033[1;34m
ED = \033[0m

all : $(NAME)

$(NAME) :
	gcc -Wextra -Werror -Wall -c *.c libft.h
	ar rc $(NAME) *.o

clean :
	/bin/rm -f *.o
	/bin/rm -f *.gch

fclean : clean
	/bin/rm -f $(NAME)

re : fclean all

